language: python
python: 
  - "3.4"
install:
  - pip install -r requirements.txt
  # - pip install flake8
  # - pip install coveralls
script:
  # - flake8 . --ignore=F405,F403
  - python test.py
  - coverage run --source=. test.py
after_success:
  - coveralls

